### ISSUE TITLE
Typo in Acronym for Azure Kubernetes Service in flowchart

### ISSUE THREAD

**Issue by anishi1222** [MicrosoftDocs/architecture-center.ja-jp#37]
Hi, 
The acronym for Azure Kubernetes Service is not AKS but ASK in flowchart Japanese edition. 
https://docs.microsoft.com/ja-jp/azure/architecture/guide/technology-choices/compute-decision-tree#flowchart
Could you please check and correct typo?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Azure コンピューティング サービスのデシジョン ツリー - Azure Application Architecture Guide](https://docs.microsoft.com/ja-jp/azure/architecture/guide/technology-choices/compute-decision-tree#flowchart)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center.ja-jp/blob/live/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
Hello, @anishi1222 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @anishi1222
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/architecture/guide/technology-choices/compute-decision-tree#flowchart

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
