### ISSUE TITLE
 Edgeでイマーシブ リーダーに切り替えると日本語と英語が交互に混在

### ISSUE THREAD

**Issue by cweuphoria** [MicrosoftDocs/architecture-center.ja-jp#49]
Edgeでイマーシブ リーダーに切り替えると日本語と英語が交互に混在します。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: cf328b1f-6bc5-dff2-619f-82b95030c3cf
* Version Independent ID: 4c7bd8b7-5ebb-5b1e-010b-2acd7fdcec0f
* Content: [Azure IoT 参照アーキテクチャ - Azure Reference Architectures](https://docs.microsoft.com/ja-jp/azure/architecture/reference-architectures/iot)
* Content Source: [docs/reference-architectures/iot.md](https://github.com/microsoftdocs/architecture-center.ja-jp/blob/live/docs/reference-architectures/iot.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by srvbpigh** [comment]
Hello, @cweuphoria
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/architecture-center #2156](https://github.com/MicrosoftDocs/architecture-center/issues/2156) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
こんにちは、@cweuphoria  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/architecture-center/issues/2156) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team
